In [2]:
import numpy as np

### 1. Create a null vector of size 10 but the fifth value which is 1.


In [3]:

arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.

In [5]:
arr1 = np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. Create a 3x3 matrix with values ranging from 0 to 8


In [8]:
arr2 = np.arange(0,9)
arr2 = arr2.reshape((3,3))
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [9]:
arr3 = np.array([1,2,0,0,4,0])
arr3.nonzero()


(array([0, 1, 4], dtype=int64),)

### 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [12]:
arr4 = np.random.randint(0,10000,(10,10))
print(arr4)
print('maximum: ',arr4.max())
print('minimum: ',arr4.min())

[[8835 4217 7984 7834 8946 6465 4525 9963 1322 9811]
 [2833 7726  644   94 8203 6948 5655 6582 3451 3427]
 [8654 5726  146 1267 5688 3054 3993 1756 4392  526]
 [4390    9 4147 1275 3000 5407 5726 5307 9441 6636]
 [1802 9378 9395  180 4537 8732 4310 7341 6475 8877]
 [2066 7181 2291 5204 5043 1357 6771 4013 1172 6472]
 [5698 9805 6069 7493 3076 6211 7390 4814 3724 1702]
 [7461 6516 9535  348 1999 4862 8230  871 7306 4211]
 [3687 6386 1372 7724 8297 3498  884 9667 6976 5276]
 [8205 9382 3729 8356 9055 4273 2951 7647 6765 2132]]
maximum:  9963
minimum:  9


### 6. Create a random vector of size 30 and find the mean value.

In [13]:
arr5 = np.random.randint(0,1234,(30))
print(arr5)
print('mean: ',arr5.mean())

[ 747  563 1176  291  887  722  772 1041 1222 1061  321 1154 1037  977
  335 1120   78  258  378  398 1079  181  527  551  183  434   51  870
  288  417]
mean:  637.3
